### ISSUE TITLE
rgb input is always converted to grayscale

### ISSUE THREAD

**Issue by TimScherr** [hip-satomi/microbeSEG#2]
So far, microbeSEG extracts the selected channel from the images. However, there may be cases, where the rgb information should be kept for annotation and model training, e.g. for histopathological images.

Goal: branch with rgb support (data cropping, model training + augmentation, inference)

**Comment by eyildiz-ugoe** [comment]
Hi, is there an update on this?

**Comment by TimScherr** [comment]
Not yet, maybe tomorrow.

**Comment by TimScherr** [comment]
The rgb training data generation works now in the branch 'rgb' and you can create the needed training data crops. However, Data import & export, training, evaluation and inference still need to be adapted.
